FROM ubuntu:12.04
MAINTAINER jhreact <jhreact@users.noreply.github.com>
RUN apt-get update

RUN apt-get install -y -q vim
RUN apt-get install -y -q htop
RUN apt-get install -y -q curl
RUN apt-get install -y -q wget
RUN apt-get install -y -q git
RUN apt-get install -y -q tmux
